# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'BarcodeScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BarcodeScanner
  pod 'SQFeedbackGenerator' # for generating haptic events
  pod 'MBProgressHUD' # for display of the HUD (loading, downloading, etc.)
  target 'BarcodeScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarcodeScannerUITests' do
    # Pods for testing
  end

end
